# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/clk_division/clk_division.xci
# IP: The module: 'clk_division' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/clk_division/clk_division_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_division'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/clk_division/clk_division.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_division'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/clk_division/clk_division_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_division'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/clk_division/clk_division.xci
# IP: The module: 'clk_division' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/clk_division/clk_division_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_division'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/clk_division/clk_division.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_division'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/clk_division/clk_division_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_division'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
