# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/Driver_ADC_0/Driver_ADC_0.xci
# IP: The module: 'Driver_ADC_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/Driver_ADC_0/src/Wave_Ram/Wave_Ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Wave_Ram || ORIG_REF_NAME==Wave_Ram} -quiet] -quiet

# XDC: c:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/Driver_ADC_0/src/Wave_Ram/Wave_Ram_ooc.xdc

# IP: c:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/Driver_ADC_0/Driver_ADC_0.xci
# IP: The module: 'Driver_ADC_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/Driver_ADC_0/src/Wave_Ram/Wave_Ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Wave_Ram || ORIG_REF_NAME==Wave_Ram} -quiet] -quiet

# XDC: c:/Users/Dell20/Desktop/xilinx/DDS_Addr_Generator/DDS_Addr_Generator.srcs/sources_1/ip/Driver_ADC_0/src/Wave_Ram/Wave_Ram_ooc.xdc
